spring:
  application:
    name: microservice-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/dh
  cloud:
    gateway:
    # TokenRelay es un filtro que propaga el token hacia los servicios
      default-filters:
      - TokenRelay=
      routes:
        - id: microservice-checkout
          uri: lb://microservice-checkout
          predicates:
            - Path=/checkouts/**
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Red, Blue
        - id: microservice-product
          uri: lb://microservice-product
          predicates:
            - Path=/products/**
    config:
      discovery:
        enabled: true
        serviceId: microservice-config

server:
  port: 8080
