spring:
  application:
    name: microservice-product

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: microservice-product
    description: descripcion desde github
    version: 1.0.0

eureka:
  instance:
    statusPageUrlPath: http://localhost:8090/actuator/info
    healthCheckUrlPath: http://localhost:8090/actuator/health
